source "https://rubygems.org"
# This site is built for GitHub Pages. github-pages locks the exact Jekyll,
# theme, and plugin versions GitHub's build servers use. To upgrade, bump
# the version below and run `bundle update github-pages`.
gem "github-pages", "232", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.2.0", :platforms => [:mingw, :x64_mingw, :mswin]


gem "webrick", "~> 1.7"
